"""
Route handlers for the anomalies resource.

Exposes read-only access to anomaly records generated by the anomaly detection
pipeline.  Supports global listing with filters and per-room listing.
"""

from datetime import datetime
from typing import Annotated, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import Anomaly, Room, get_db
from app.models import AnomalyResponse

router = APIRouter(prefix="/api", tags=["anomalies"])

DB = Annotated[AsyncSession, Depends(get_db)]


@router.get("/anomalies", response_model=list[AnomalyResponse])
async def list_anomalies(
    db: DB,
    room_id: Annotated[Optional[str], Query()] = None,
    from_date: Annotated[Optional[datetime], Query()] = None,
    to_date: Annotated[Optional[datetime], Query()] = None,
    limit: Annotated[int, Query(ge=1, le=10000)] = 100,
):
    query = select(Anomaly).order_by(Anomaly.timestamp.desc()).limit(limit)

    if room_id is not None:
        query = query.where(Anomaly.room_id == room_id)
    if from_date is not None:
        query = query.where(Anomaly.timestamp >= from_date)
    if to_date is not None:
        query = query.where(Anomaly.timestamp <= to_date)

    result = await db.execute(query)
    return result.scalars().all()


@router.get("/rooms/{room_id}/anomalies", response_model=list[AnomalyResponse])
async def list_room_anomalies(
    room_id: str,
    db: DB,
    limit: Annotated[int, Query(ge=1, le=10000)] = 100,
):
    room_result = await db.execute(select(Room).where(Room.id == room_id))
    if room_result.scalar_one_or_none() is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Room not found")

    result = await db.execute(
        select(Anomaly)
        .where(Anomaly.room_id == room_id)
        .order_by(Anomaly.timestamp.desc())
        .limit(limit)
    )
    return result.scalars().all()
